version: "3"
services: 
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/cookie0512/note-springboot:3.0
    container_name: "backend"
    volumes: 
    - ./my-note/project/:/project/
    - ./my-note/entrypoint.sh:/entrypoint.sh
    - ./my-note/settings.xml:/usr/share/maven/conf/settings.xml
    entrypoint: 
    - /entrypoint.sh
    depends_on: 
    - myes
    - mymysql
    - myredis
    # ports: 
    # - 8081:8080
    # - 5005:5005
    network_mode: host
  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/cookie0512/note-vue:2.0
    container_name: vue
    volumes: 
    # - ./vue-project/project/:/project/
    - ./vue-project/entrypoint.sh:/entrypoint.sh
    entrypoint: 
    - /entrypoint.sh
    # ports: 
    # - 8082:8080
    depends_on: 
    - backend
    network_mode: host
  mymysql:
    image: mysql
    container_name: mymysql
    volumes: 
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment: 
    - MYSQL_ROOT_PASSWORD=123456
    privileged: true
    # ports: 
    # - 3307:3306
    network_mode: host
  myes:
    image: elasticsearch:6.8.6
    container_name: myes
    volumes: 
    - ./elasticsearch/ik/:/usr/share/elasticsearch/plugins/ik/
    environment:
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    # ports: 
    # - 9301:9300
    network_mode: host
  myredis:
    image: redis
    container_name: myredis
    # ports: 
    # - 6380:6379
    network_mode: host
# 将my-note里的project和my-entrypoint.sh 映射到容器中
# 设置entrypoint为 my-entrypoint.sh